// <auto-generated />
using System;
using LeanKernel.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeanKernel.Persistence.Migrations
{
    [DbContext(typeof(LeanKernelDbContext))]
    [Migration("20250527191827_AddDocumentIngestionJobs")]
    /// <summary>
    /// Migration metadata snapshot for document ingestion jobs schema changes.
    /// </summary>
    partial class AddDocumentIngestionJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeanKernel.Persistence.Entities.CapabilityGapEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportanceFactor")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("CapabilityGaps", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.CompactionMarkerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CompactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NewHistorySize")
                        .HasColumnType("bigint");

                    b.Property<long>("OriginalHistorySize")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("CompactedAt");

                    b.ToTable("CompactionMarkers", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.DiagnosticEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("DiagnosticEntries", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.DocumentIngestionJobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("DocumentIngestionJobs", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.ScheduledJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExecutionLog")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NextRunAfterSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobName");

                    b.HasIndex("StartedAt");

                    b.HasIndex("JobName", "ScheduledAt");

                    b.ToTable("ScheduledJobs", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique();

                    b.ToTable("Sessions", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.TurnEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssistantResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Turns", "engine");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.CapabilityGapEntity", b =>
                {
                    b.HasOne("LeanKernel.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("CapabilityGaps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.CompactionMarkerEntity", b =>
                {
                    b.HasOne("LeanKernel.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("CompactionMarkers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.DiagnosticEntryEntity", b =>
                {
                    b.HasOne("LeanKernel.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("DiagnosticEntries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.TurnEntity", b =>
                {
                    b.HasOne("LeanKernel.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LeanKernel.Persistence.Entities.SessionEntity", b =>
                {
                    b.Navigation("CapabilityGaps");

                    b.Navigation("CompactionMarkers");

                    b.Navigation("DiagnosticEntries");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
