using LeanKernel.Core.Models;

namespace LeanKernel.Core.Interfaces;

/// <summary>
/// Enhances an assistant response before it is returned to the user.
/// </summary>
public interface IResponseEnhancer
{
    /// <summary>
    /// Enhances a response using the current request and selected conversation context.
    /// </summary>
    /// <param name="userQuery">The user's request.</param>
    /// <param name="assistantResponse">The response generated by the model.</param>
    /// <param name="context">The context selected for the turn.</param>
    /// <param name="ct">A token used to cancel enhancement.</param>
    /// <returns>The enhanced response, or the original response when no enhancement is applied.</returns>
    Task<string> EnhanceResponseAsync(
        string userQuery,
        string assistantResponse,
        ConversationContext context,
        CancellationToken ct);
}
