using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LeanKernel.Generators;

/// <summary>
/// Roslyn incremental source generator that discovers all classes annotated
/// with [ToolMetadata] and generates a static ToolRegistry at compile time.
/// This eliminates runtime reflection for tool discovery.
/// </summary>
[Generator]
public class ToolRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations with any attribute named "ToolMetadata"
        var toolClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => IsToolCandidate(node),
                transform: (ctx, _) => GetToolInfo(ctx))
            .Where(info => info != null);

        var collected = toolClasses.Collect();
        context.RegisterSourceOutput(collected, GenerateRegistry);
    }

    private static bool IsToolCandidate(SyntaxNode node)
    {
        if (!(node is ClassDeclarationSyntax classDecl)) return false;
        foreach (var attrList in classDecl.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var name = attr.Name.ToString();
                if (name == "ToolMetadata" || name == "ToolMetadataAttribute" || name.EndsWith(".ToolMetadata"))
                    return true;
            }
        }
        return false;
    }

    private static ToolInfo GetToolInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "ToolMetadataAttribute");
        if (attr == null) return null;

        var (name, description, category) = ReadToolMetadata(attr);

        if (name == null || description == null) return null;

        return new ToolInfo(
            symbol.ToDisplayString(),
            name,
            description,
            category);
    }

    private static (string Name, string Description, string Category) ReadToolMetadata(AttributeData attr)
    {
        string name = null;
        string description = null;
        string category = "General";

        foreach (var arg in attr.NamedArguments)
        {
            switch (arg.Key)
            {
                case "Name":
                    name = arg.Value.Value as string;
                    break;
                case "Description":
                    description = arg.Value.Value as string;
                    break;
                case "Category":
                    category = arg.Value.Value?.ToString() ?? category;
                    break;
            }
        }

        return (name, description, category);
    }

    private static void GenerateRegistry(
        SourceProductionContext context,
        ImmutableArray<ToolInfo> tools)
    {
        // Filter nulls
        var validTools = tools.Where(t => t != null).ToArray();
        if (validTools.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace LeanKernel.Plugins.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated tool registry. Zero-reflection tool discovery.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedToolRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Type> ToolTypes = new Dictionary<string, System.Type>");
        sb.AppendLine("    {");
        foreach (var tool in validTools)
        {
            sb.Append("        [\"").Append(tool.ToolName).Append("\"] = typeof(").Append(tool.ClassName).AppendLine("),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.Append("    public static readonly int Count = ").Append(validTools.Length).AppendLine(";");
        sb.AppendLine("}");

        context.AddSource("GeneratedToolRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal sealed class ToolInfo
{
    public ToolInfo(string className, string toolName, string description, string category)
    {
        ClassName = className;
        ToolName = toolName;
        Description = description;
        Category = category;
    }

    public string ClassName { get; }
    public string ToolName { get; }
    public string Description { get; }
    public string Category { get; }
}
